window.products = [
  {
    id: 1,
    name: "LuminoTech LED Desk Lamp",
    price: 19.99,
    sku: "SKU001",
    qty: 10,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 2,
    name: "SwiftGear Wireless Earbuds",
    price: 29.99,
    sku: "SKU002",
    qty: 5,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 3,
    name: "FrostyBrew Portable Coffee Maker",
    price: 9.99,
    sku: "SKU003",
    qty: 2,
    status: "Out of stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 4,
    name: "ZephyrFit Fitness Tracker",
    price: 49.99,
    sku: "SKU004",
    qty: 15,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: true,
    selected: false,
  },
  {
    id: 5,
    name: "AquaWave Waterproof Bluetooth Speaker",
    price: 14.99,
    sku: "SKU005",
    qty: 7,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 6,
    name: "EcoCleanse Organic Laundry Detergent",
    price: 39.99,
    sku: "SKU006",
    qty: 0,
    status: "Out of stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 7,
    name: "PawsomePet Automatic Pet Feeder",
    price: 24.99,
    sku: "SKU007",
    qty: 12,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 8,
    name: "SleepWell Memory Foam Pillow",
    price: 64.99,
    sku: "SKU008",
    qty: 3,
    status: "Out of stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 9,
    name: "PowerBoost Portable Phone Charger",
    price: 11.99,
    sku: "SKU009",
    qty: 8,
    status: "Out of stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 10,
    name: "LunaGlow Facial Cleansing Brush",
    price: 79.99,
    sku: "SKU010",
    qty: 4,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 11,
    name: "NatureTrail Hiking Backpack",
    price: 9.99,
    sku: "SKU011",
    qty: 6,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 12,
    name: "ZenTune Meditation Headphones",
    price: 19.99,
    sku: "SKU012",
    qty: 1,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 13,
    name: "ChillBliss Cooling Weighted Blanket",
    price: 34.99,
    sku: "SKU013",
    qty: 9,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 14,
    name: "EnergiFlex Smart Power Strip",
    price: 44.99,
    sku: "SKU014",
    qty: 11,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 15,
    name: "SnapFit Phone Camera Lens Kit",
    price: 7.99,
    sku: "SKU015",
    qty: 0,
    status: "Out of stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 16,
    name: "InfinityPro Hair Straightener",
    price: 59.99,
    sku: "SKU016",
    qty: 13,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 17,
    name: "WonderGarden Indoor Herb Kit",
    price: 27.99,
    sku: "SKU017",
    qty: 6,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 18,
    name: "TruSonic Ultrasonic Jewelry Cleaner",
    price: 21.99,
    sku: "SKU018",
    qty: 3,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 19,
    name: "PlayMuse Bluetooth Game Controller",
    price: 49.99,
    sku: "SKU019",
    qty: 8,
    status: "In stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  },
  {
    id: 20,
    name: "VitaBlend Nutrient Extractor",
    price: 12.99,
    sku: "SKU020",
    qty: 0,
    status: "Out of stock",
    image: "https://picsum.photos/80/80",
    deleted: false,
    selected: false,
  }
];

window.orders = [
  {
    orderId: 20,
    customer: "John Doe",
    total: 119.97,
    status: "Pending",
  },
  {
    orderId: 19,
    customer: "Jane Smith",
    total: 97.95,
    status: "Cancelled",
  },
  {
    orderId: 18,
    customer: "David Johnson",
    total: 254.94,
    status: "Paid",
  },
  {
    orderId: 17,
    customer: "Emily Davis",
    total: 149.95,
    status: "Paid",
  },
  {
    orderId: 16,
    customer: "Michael Wilson",
    total: 174.97,
    status: "Paid",
  },
  {
    orderId: 15,
    customer: "Sarah Thompson",
    total: 189.98,
    status: "Shipped",
  },
  {
    orderId: 14,
    customer: "Robert Martinez",
    total: 109.97,
    status: "Shipped",
  },
  {
    orderId: 13,
    customer: "Jennifer Anderson",
    total: 79.98,
    status: "Shipped",
  },
  {
    orderId: 12,
    customer: "Christopher Brown",
    total: 169.97,
    status: "Cancelled",
  },
  {
    orderId: 11,
    customer: "Laura Davis",
    total: 109.97,
    status: "Shipped",
  },
  {
    orderId: 10,
    customer: "Matthew Taylor",
    total: 144.97,
    status: "Delivered",
  },
  {
    orderId: 9,
    customer: "Jessica Wilson",
    total: 189.97,
    status: "Delivered",
  },
  {
    orderId: 8,
    customer: "Daniel Johnson",
    total: 199.97,
    status: "Delivered",
  },
  {
    orderId: 7,
    customer: "Sophia Anderson",
    total: 84.97,
    status: "Delivered",
  },
  {
    orderId: 6,
    customer: "Alexander Smith",
    total: 144.97,
    status: "Delivered",
  },
  {
    orderId: 5,
    customer: "Olivia Thompson",
    total: 89.99,
    status: "Cancelled",
  },
  {
    orderId: 4,
    customer: "William Martinez",
    total: 119.98,
    status: "Delivered",
  },
  {
    orderId: 3,
    customer: "Ava Davis",
    total: 109.99,
    status: "Delivered",
  },
  {
    orderId: 2,
    customer: "James Wilson",
    total: 99.99,
    status: "Delivered",
  },
  {
    orderId: 1,
    customer: "Mia Thompson",
    total: 134.97,
    status: "Delivered",
  }
];

window.search = [
  {
    "caption": "Shop / Products",
    "url": "/products/",
    "icon": "<path d='M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z'></path><line x1='3' y1='6' x2='21' y2='6'></line><path d='M16 10a4 4 0 0 1-8 0'></path>"
  },
  {
    "caption": "Shop / Orders",
    "url": "/orders/",
    "icon": "<circle cx='9' cy='21' r='1'></circle><circle cx='20' cy='21' r='1'></circle><path d='M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6'></path>"
  },
  {
    "caption": "Shop / Customers",
    "url": "/customers/",
    "icon": "<path d='M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'></path><circle cx='9' cy='7' r='4'></circle><path d='M23 21v-2a4 4 0 0 0-3-3.87'></path><path d='M16 3.13a4 4 0 0 1 0 7.75'></path>"
  },
  {
    "caption": "Shop / Categories",
    "url": "/categories/",
    "icon": "<polyline points='21 8 21 21 3 21 3 8'></polyline><rect x='1' y='3' width='22' height='5'></rect><line x1='10' y1='12' x2='14' y2='12'></line>"
  },
  {
    "caption": "Account",
    "url": "/account/",
    "icon": null
  },
  {
    "caption": "Settings",
    "url": "/settings/",
    "icon": null
  }
];
